/* Create an interface similar to fromUser. */
export type ibmiUserInterface = {
	AUTHORIZATION_NAME: string;
	PREVIOUS_SIGNON: string;
	SIGN_ON_ATTEMPTS_NOT_VALID: number;
	MAXIMUM_SIGN_ON_ATTEMPTS: string;
	STATUS: string;
	NETSERVER_DISABLED: string;
	PASSWORD_CHANGE_DATE: string;
	NO_PASSWORD_INDICATOR: string;
	PASSWORD_LEVEL_0_1: string;
	PASSWORD_LEVEL_2_3: string;
	PASSWORD_LEVEL_4: string;
	PASSWORD_EXPIRATION_INTERVAL: number;
	DATE_PASSWORD_EXPIRES: string;
	DAYS_UNTIL_PASSWORD_EXPIRES: string | null;
	SET_PASSWORD_TO_EXPIRE: string;
	USER_CLASS_NAME: string;
	SPECIAL_AUTHORITIES: string | null;
	GROUP_PROFILE_NAME: string;
	SUPPLEMENTAL_GROUP_COUNT: number;
	SUPPLEMENTAL_GROUP_LIST: string | null;
	OWNER: string;
	GROUP_AUTHORITY: string;
	ASSISTANCE_LEVEL: string;
	CURRENT_LIBRARY_NAME: string;
	INITIAL_MENU_NAME: string;
	INITIAL_MENU_LIBRARY_NAME: string;
	INITIAL_PROGRAM_NAME: string;
	INITIAL_PROGRAM_LIBRARY_NAME: string;
	LIMIT_CAPABILITIES: string;
	TEXT_DESCRIPTION: string;
	DISPLAY_SIGNON_INFORMATION: string;
	LIMIT_DEVICE_SESSIONS: string;
	KEYBOARD_BUFFERING: string;
	MAXIMUM_ALLOWED_STORAGE: bigint;
	STORAGE_USED: bigint;
	HIGHEST_SCHEDULING_PRIORITY: string;
	JOB_DESCRIPTION_NAME: string;
	JOB_DESCRIPTION_LIBRARY_NAME: string;
	ACCOUNTING_CODE: string | null;
	MESSAGE_QUEUE_NAME: string;
	MESSAGE_QUEUE_LIBRARY_NAME: string;
	MESSAGE_QUEUE_DELIVERY_METHOD: string;
	MESSAGE_QUEUE_SEVERITY: number;
	OUTPUT_QUEUE_NAME: string;
	OUTPUT_QUEUE_LIBRARY_NAME: string;
	PRINT_DEVICE: string;
	SPECIAL_ENVIRONMENT: string;
	ATTENTION_KEY_HANDLING_PROGRAM_NAME: string;
	ATTENTION_KEY_HANDLING_PROGRAM_LIBRARY_NAME: string;
	LANGUAGE_ID: string;
	COUNTRY_OR_REGION_ID: string;
	CHARACTER_CODE_SET_ID: string;
	USER_OPTIONS: string;
	SORT_SEQUENCE_TABLE_NAME: string;
	SORT_SEQUENCE_TABLE_LIBRARY_NAME: string | null;
	OBJECT_AUDITING_VALUE: string;
	USER_ACTION_AUDIT_LEVEL: string | number | null;
	GROUP_AUTHORITY_TYPE: string;
	USER_ID_NUMBER: bigint;
	GROUP_ID_NUMBER: bigint;
	LOCALE_JOB_ATTRIBUTES: string;
	GROUP_MEMBER_INDICATOR: string;
	DIGITAL_CERTIFICATE_INDICATOR: string;
	CHARACTER_IDENTIFIER_CONTROL: string;
	LOCAL_PASSWORD_MANAGEMENT: string;
	BLOCK_PASSWORD_CHANGE: string;
	USER_ENTITLEMENT_REQUIRED: string;
	USER_EXPIRATION_INTERVAL: number;
	USER_EXPIRATION_DATE: null;
	USER_EXPIRATION_ACTION: string;
	HOME_DIRECTORY: string;
	LOCALE_PATH_NAME: string;
	USER_DEFAULT_PASSWORD: null;
	USER_OWNER: string;
	USER_CREATOR: string;
	SIZE: number;
	CREATION_TIMESTAMP: string;
	LAST_USED_TIMESTAMP: string;
	DAYS_USED_COUNT: number;
	LAST_RESET_TIMESTAMP: null;
	AUTHORITY_COLLECTION_ACTIVE: string;
	AUTHORITY_COLLECTION_REPOSITORY_EXISTS: string;
	PASE_SHELL_PATH: string | null;
};
export type createUserInterface = {
	userId: string;
	userText: string;
	userPassword: string;
	userClass: string;
	userInitialProgram: string;
	userInitialMenu: string;
	userLimitCapabilities: string;
	userSpecialAuthority: string;
	userJobDescription: string;
	userGroupProfile: string;
	userGroupAuthority: string;
	userAccountingCode: string;
	userDelivery: string;
	userOutqueue: string;
	userAttentionProgram: string;
	userSupplementalGroups: string;
};
